require("zetsumei.plugins-setup")
require("zetsumei.core.options")
require("zetsumei.core.keymaps")
require("zetsumei.core.colorscheme")
require("zetsumei.plugins.comment")
require("zetsumei.plugins.nvim-tree")
require("zetsumei.plugins.lualine")
require("zetsumei.plugins.telescope")
require("zetsumei.plugins.lsp-config")
require("zetsumei.plugins.completions")
require("zetsumei.plugins.rich-presence")
require("zetsumei.plugins.transparent")
require("zetsumei.plugins.indent-blankline")
vim.g.strip_whitespace_confirm = 0
